version: "3"

## Containers ##
services:
  wordpress:
    image: wordpress
    ports:
      - "8089:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "coffee"
      WORDPRESS_DB_BANE: wordpress
    networks:
      ohyeah:
        ipv4_address: "10.56.1.21"
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "coffee"
    volumes:
      - ./msql:/var/lib/mysql
    networks:
      ohyeah:
        ipv4_address: "10.56.1.20"


## Network Definition ##
networks:
  ohyeah:
  ipam:
    driver: default
    config:
      - "10.56.1.0/24"


#   website:
#   image: nginx
#   ports:
#     - "8081:80"
#   restart: always

# website2:
#   image: nginx
#   ports:
#     - "8082:80"
#   restart: always
#   networks:
#     coffee:
#       ipv4_address: 192.168.92.21

# networks:
#   coffee:
#   ipam:
#     driver: default
#     config:
#       - subnet: "192.168.92.0/24"

